
INSERT into emp1287675(emp_id,email,department-id,dept_id )
select employee_id,


insert into emp1287675(E_NAME,E_ID,)






INSERT INTO emp1287675(E_ID,E_NAME,SALARY,HIRE_DATE,ADDRESS,DEPARTMENT_NAME)
 VALUES (01,'Rakib',5000,'01-JAN-08','Null','JEE');
 
 INSERT INTO emp1287675(E_ID,E_NAME,SALARY,HIRE_DATE,ADDRESS,DEPARTMENT_NAME)
 VALUES (02,'Parvez',5000,'01-FEB-04','Null','DDD');
 
 INSERT INTO emp1287675(E_ID,E_NAME,SALARY,HIRE_DATE,ADDRESS,DEPARTMENT_NAME)
  VALUES (03,'Eiasin',5000,'01-DEC-03','Null','JEE');
  
  INSERT INTO emp1287675(E_ID,E_NAME,SALARY,HIRE_DATE,ADDRESS,DEPARTMENT_NAME)
  VALUES (04,'Arif',5000,'01-JAN-08','Null','NT');
  
  
  select*from emp1287675;
  
  COMMIT;
  
  
  
update emp1287675 set E_NAME = 'Sakib'
where E_ID=4;




SELECT JOB_ID
FROM EMPLOYEES
WHERE SALARY>(SELECT SALARY
            FROM EMPLOYEES
            WHERE AVG(SALARY)>10000);


SELECT JOB_ID
            FROM EMPLOYEES
       WHERE 10000<AVG(SALARY);
       
  SELECT JOB_ID
 FROM EMPLOYEES
 GROUP BY JOB_ID
 HAVING AVG(SALARY)>10000;     
       
       
       
       
 SELECT JOB_ID
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN( SELECT JOB_ID
 FROM EMPLOYEES
 GROUP JOB_ID
 HAVING AVG(SALARY)>10000);


       
 SELECT JOB_ID
 FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN( SELECT JOB_ID
 FROM EMPLOYEES
 GROUP JOB_ID
 HAVING AVG(SALARY)>10000);





